"""record when an order was captured

Capture used to be inferred from status, and the inference inverted when the
capture moved from ship to confirm: `confirmed` meant "not captured" before and
"captured" after. An order in flight across that deploy would therefore have
shipped without the money ever being taken, and cancelling it would have
attempted a refund on an uncaptured intent - which Stripe rejects, leaving an
order that could not be cancelled at all.

NULL is the honest default for existing rows: nothing here knows whether they
were captured, and claiming otherwise is what caused the problem. The ship path
captures when it finds NULL, so orders confirmed under the old rule are picked
up on their way out rather than needing a backfill that would have to guess.

Revision ID: 86cb588259cd
Revises: e17c9ef72db1
Create Date: 2026-09-06 23:19:08.087473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86cb588259cd'
down_revision: Union[str, Sequence[str], None] = 'e17c9ef72db1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'captured_at')
    # ### end Alembic commands ###
