"""save the cart server side

Revision ID: a68c1d2fcf31
Revises: 86cb588259cd
Create Date: 2026-09-08 20:55:23.299338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a68c1d2fcf31'
down_revision: Union[str, Sequence[str], None] = '86cb588259cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_kind', sa.String(length=16), server_default='user', nullable=False),
    sa.Column('owner_id', sa.String(length=255), nullable=False),
    sa.Column('variant_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_cart_items_quantity_positive'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_kind', 'owner_id', 'variant_id', name='uq_cart_owner_variant')
    )
    op.create_index(op.f('ix_cart_items_owner_id'), 'cart_items', ['owner_id'], unique=False)
    op.create_index(op.f('ix_cart_items_updated_at'), 'cart_items', ['updated_at'], unique=False)
    op.create_index(op.f('ix_cart_items_variant_id'), 'cart_items', ['variant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cart_items_variant_id'), table_name='cart_items')
    op.drop_index(op.f('ix_cart_items_updated_at'), table_name='cart_items')
    op.drop_index(op.f('ix_cart_items_owner_id'), table_name='cart_items')
    op.drop_table('cart_items')
    # ### end Alembic commands ###
