"""add tax_amount to orders and checkout_sessions

Revision ID: c09c8c1b08ed
Revises: 55894e29c942
Create Date: 2026-05-28 23:14:01.900416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c09c8c1b08ed'
down_revision: Union[str, Sequence[str], None] = '55894e29c942'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checkout_sessions', sa.Column('tax_amount_cents', sa.Integer(), server_default='0', nullable=False))
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.add_column('orders', sa.Column('tax_amount', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'tax_amount')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_column('checkout_sessions', 'tax_amount_cents')
    # ### end Alembic commands ###
