"""cart lines carry a client clock and a tombstone

Revision ID: c2c37138d24e
Revises: a68c1d2fcf31
Create Date: 2026-09-08 23:34:02.184740

Existing rows default client_updated_at to now() at migration time - the last
edit any of them actually saw is unrecoverable, and "now" is the safe answer:
it makes a pre-existing row look freshly edited rather than ancient, so it can
still win a conflict against a device that has been offline since before this
migration ran, which is exactly the customer this feature is for.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2c37138d24e'
down_revision: Union[str, Sequence[str], None] = 'a68c1d2fcf31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_items', sa.Column('client_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('cart_items', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart_items', 'deleted_at')
    op.drop_column('cart_items', 'client_updated_at')
    # ### end Alembic commands ###
