"""index the foreign keys and constrain what cannot be negative

Two things the baseline schema left out.

**Foreign keys were unindexed.** Postgres indexes a primary key and a unique
constraint for you; it does not index a foreign key. So `product_variants.product_id`,
`order_items.variant_id` and `product_tags.tag_id` had none, which means loading
a product's variants scanned the table, and the `ON DELETE SET NULL` on a
variant scanned every order item ever written.

**Nothing was constrained.** There was not a single CHECK in the database.
`orders.status` is a varchar because the model asks for `native_enum=False`, and
SQLAlchemy has defaulted `create_constraint` to False since 1.4 - so any string
at all could be written there. Quantities could be zero, stock could go negative,
prices could be negative. The application refuses all of that, which is precisely
why guaranteeing it costs nothing.

The composite index on (status, created_at) is for the admin order list, which
is "newest first, optionally one status". Leading with status lets one index
serve both the filtered tabs and the unfiltered one.

All of these were checked against the existing data before being added: zero
rows violate any of them.

Revision ID: dd0437f34880
Revises: 8d7274b0c28f
Create Date: 2026-09-05 22:19:37.553836

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'dd0437f34880'
down_revision: Union[str, Sequence[str], None] = '8d7274b0c28f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

ORDER_STATUSES = (
    "pending",
    "awaiting_fulfillment",
    "confirmed",
    "shipped",
    "delivered",
    "cancelled",
)

# (table, constraint name, condition)
CHECKS = [
    ("orders", "ck_orders_total_not_negative", "total_amount >= 0"),
    ("orders", "ck_orders_tax_not_negative", "tax_amount >= 0"),
    (
        "orders",
        "ck_orders_status",
        "status IN (" + ", ".join(f"'{s}'" for s in ORDER_STATUSES) + ")",
    ),
    ("order_items", "ck_order_items_quantity_positive", "quantity > 0"),
    ("order_items", "ck_order_items_price_not_negative", "unit_price >= 0"),
    ("product_variants", "ck_variants_stock_not_negative", "stock >= 0"),
    ("product_variants", "ck_variants_price_not_negative", "price >= 0"),
    ("product_variants", "ck_variants_size_positive", "size_value > 0"),
]


def upgrade() -> None:
    """Upgrade schema."""
    op.create_index(op.f('ix_checkout_sessions_created_at'), 'checkout_sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_order_items_variant_id'), 'order_items', ['variant_id'], unique=False)
    op.create_index('ix_orders_status_created_at', 'orders', ['status', 'created_at'], unique=False)
    op.create_index('ix_product_tags_tag_id', 'product_tags', ['tag_id'], unique=False)
    op.create_index(op.f('ix_product_variants_product_id'), 'product_variants', ['product_id'], unique=False)

    # Written out rather than autogenerated: alembic does not compare
    # CheckConstraints, so these would never appear in a --autogenerate diff and
    # `alembic check` will not notice if they are dropped.
    for table, name, condition in CHECKS:
        op.create_check_constraint(name, table, condition)


def downgrade() -> None:
    """Downgrade schema."""
    for table, name, _ in reversed(CHECKS):
        op.drop_constraint(name, table, type_="check")

    op.drop_index(op.f('ix_product_variants_product_id'), table_name='product_variants')
    op.drop_index('ix_product_tags_tag_id', table_name='product_tags')
    op.drop_index('ix_orders_status_created_at', table_name='orders')
    op.drop_index(op.f('ix_order_items_variant_id'), table_name='order_items')
    op.drop_index(op.f('ix_checkout_sessions_created_at'), table_name='checkout_sessions')
