"""charge for shipping

The shop charged goods plus tax and nothing for postage, which for reagents
going out cold is a real cost absorbed on every order.

Both columns default to 0.00, so existing rows and any environment that has not
set SHIPPING_FLAT_CENTS keep behaving exactly as before rather than acquiring a
charge nobody chose. Orders written before this keep adding up to what was
actually taken.

checkout_sessions carries it too: the webhook builds the order from that row
minutes after checkout, and recomputing shipping there could charge a rate the
customer was never shown.

The CHECK is written out by hand. Alembic does not compare CheckConstraints, so
it appears in no --autogenerate diff and `alembic check` will not notice if it
is dropped - the same reason the constraints in dd0437f34880 are spelled out.

Revision ID: e17c9ef72db1
Revises: dd0437f34880
Create Date: 2026-09-06 20:33:38.041960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e17c9ef72db1'
down_revision: Union[str, Sequence[str], None] = 'dd0437f34880'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checkout_sessions', sa.Column('shipping_amount_cents', sa.Integer(), server_default='0', nullable=False))
    op.add_column('orders', sa.Column('shipping_amount', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=False))
    # ### end Alembic commands ###
    op.create_check_constraint(
        "ck_orders_shipping_not_negative", "orders", "shipping_amount >= 0"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ck_orders_shipping_not_negative", "orders", type_="check")
    op.drop_column('orders', 'shipping_amount')
    op.drop_column('checkout_sessions', 'shipping_amount_cents')
    # ### end Alembic commands ###
