"""add_tracking_number_to_orders

Revision ID: eea1fc0aee1c
Revises: b7e4a1c0d823
Create Date: 2026-05-29 11:18:55.980041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eea1fc0aee1c'
down_revision: Union[str, Sequence[str], None] = 'b7e4a1c0d823'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('tracking_number', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'tracking_number')
    # ### end Alembic commands ###
