from functools import lru_cache
from urllib.parse import quote

from pydantic import SecretStr, model_validator
from pydantic_settings import BaseSettings, SettingsConfigDict

PRODUCTION_ENVS = {"prod", "production"}

# Stripe issues keys per mode, and the prefix is the only thing that says which
# is which. STRIPE_MODE declares the mode the deployment is *supposed* to be in,
# so a key from the other one is a startup failure rather than a discovery.
STRIPE_MODES = {"test": "sk_test_", "live": "sk_live_"}


class Settings(BaseSettings):
    app_name: str = "oasis-backend"
    app_env: str = "dev"

    log_level: str = "INFO"
    """Root log level. An unknown value falls back to INFO rather than refusing
    to start - see app/core/logging.py."""
    api_v1_prefix: str = "/api/v1"

    # Override in production with the deployed frontend origin
    cors_origins: list[str] = ["http://localhost:5174"]

    business_timezone: str = "America/New_York"
    """The zone the admin dashboard's date windows are computed in.

    created_at is stored in UTC, where "today" rolls over in the early evening
    in US zones - an order placed at 8pm would land in tomorrow's figures and
    the dashboard would disagree with the admin's own sense of the day.

    One fixed zone rather than the viewer's: the same number should appear on a
    laptop, a phone, and from a hotel in another country.
    """

    # Set to True in local dev to skip Cognito verification
    auth_bypass: bool = False

    # Either DATABASE_URL, or the DB_* parts below. Local development sets the
    # URL directly; a deployment cannot, because the password only exists inside
    # the secret RDS generated and is injected as its own variable.
    database_url: str = ""
    db_host: str = ""
    db_port: int = 5432
    db_name: str = "oasis"
    db_user: str = ""
    # SecretStr on every credential. Pydantic renders these as "**********"
    # in any repr, which matters because a ValidationError carries the input
    # dict in its message: a misconfigured boot writes that to CloudWatch.
    # Pydantic truncates long inputs so nothing leaks today, but that is a
    # display heuristic rather than a guarantee, and the values here include
    # a live Stripe key.
    db_password: SecretStr = SecretStr("")

    # Required — must be set in .env or environment
    cognito_region: str
    cognito_user_pool_id: str
    s3_bucket_name: str
    aws_region: str
    cloudfront_url: str  # e.g. https://d1234abcd.cloudfront.net
    # Optional, and empty is the right answer in a deployed environment.
    #
    # Locally there is an IAM user's key in .env, because a laptop has no role
    # to assume. On App Runner there is an instance role, and boto3 finds it on
    # its own as long as nothing hands it a key first - see app/core/aws.py.
    # These were required until it turned out the App Runner stack sets neither,
    # so the container could not start at all.
    aws_access_key_id: str = ""
    aws_secret_access_key: SecretStr = SecretStr("")

    # The app client access tokens must have been issued to. Optional so a local
    # .env predating this check still boots; required under APP_ENV=prod by the
    # validator below, because without it any app client in the pool is accepted.
    cognito_user_pool_client_id: str = ""

    stripe_secret_key: SecretStr = SecretStr("")
    stripe_webhook_secret: SecretStr = SecretStr("")
    stripe_bypass: bool = False  # When True, skip real Stripe API calls (dev/test mode)

    email_bypass: bool = False
    """When True, log the message instead of sending it.

    The same shape as stripe_bypass, and for the same reason: local development
    and the test suite must not put mail in front of real people, and SES in
    sandbox refuses unverified recipients anyway.
    """

    email_from: str = ""
    """The SES-verified From address. Required unless email_bypass is on.

    SES will not send from an identity it has not verified, so this is the one
    piece of email configuration that cannot have a sensible default.
    """

    email_reply_to: str = ""
    """Optional. Where replies go if that is not the From address - a support
    inbox a person actually reads, rather than a no-reply nobody watches."""

    # Which Stripe mode this deployment expects: "test" or "live". Staging runs
    # "test" against real Stripe, so the webhook, manual capture and refund paths
    # are genuinely exercised without money moving. See _refuse_mismatched_stripe_mode.
    stripe_mode: str = "test"

    model_config = SettingsConfigDict(
        env_file=".env",
        env_file_encoding="utf-8",
        extra="ignore",
    )

    @model_validator(mode="after")
    def _assemble_database_url(self) -> "Settings":
        """Build DATABASE_URL from its parts when it was not given directly.

        A deployed environment cannot set the URL: the password is generated by
        RDS into a secret and injected on its own, so the connection string has
        to be assembled where the password is known - here.

        DATABASE_URL still wins when present, which keeps local development,
        the test suite and the docker-compose setup working unchanged.
        """
        if self.database_url:
            return self

        missing = [
            name
            for name, value in (
                ("DB_HOST", self.db_host),
                ("DB_USER", self.db_user),
                ("DB_PASSWORD", self.db_password.get_secret_value()),
            )
            if not value
        ]
        if missing:
            raise ValueError(
                "Set DATABASE_URL, or all of DB_HOST, DB_USER and DB_PASSWORD. "
                f"Missing: {', '.join(missing)}"
            )

        # The password is percent-encoded because it goes into a URL and RDS
        # generates it from an alphabet that can include characters SQLAlchemy
        # would otherwise read as structure - a '/' or '@' silently truncates the
        # host, and the failure looks like an unreachable database.
        password = quote(self.db_password.get_secret_value(), safe="")
        self.database_url = (
            f"postgresql+psycopg://{self.db_user}:{password}"
            f"@{self.db_host}:{self.db_port}/{self.db_name}"
        )
        return self

    @model_validator(mode="after")
    def _refuse_mismatched_stripe_mode(self) -> "Settings":
        """Refuse to start when the Stripe key does not match the declared mode.

        Two mistakes this exists to stop, both of which look completely healthy:

        Live keys in staging. Every test order charges a real card. Nobody
        notices from the application side, because the code path is identical -
        the difference is only which of Stripe's ledgers it lands in.

        Test keys in production. Every order succeeds and no money is ever taken.
        This one is worse, because the failure is silent for as long as nobody
        reconciles the books against the orders.

        The key prefix is the only thing distinguishing them, and both are
        pasted in by hand at deploy time. STRIPE_MODE is set by the
        infrastructure alongside the secret, so the two have to agree.

        Not checked under stripe_bypass, where no key is used at all.
        """
        if self.stripe_bypass:
            return self

        mode = self.stripe_mode.lower()
        if mode not in STRIPE_MODES:
            raise ValueError(
                f"STRIPE_MODE must be one of {sorted(STRIPE_MODES)}, got {self.stripe_mode!r}"
            )

        # An empty key is the concern of the production guard below, which knows
        # whether one is required here at all.
        secret_key = self.stripe_secret_key.get_secret_value()
        if secret_key and not secret_key.startswith(STRIPE_MODES[mode]):
            actual = next(
                (name for name, prefix in STRIPE_MODES.items()
                 if secret_key.startswith(prefix)),
                "neither test nor live",
            )
            raise ValueError(
                f"STRIPE_MODE is {mode!r} but STRIPE_SECRET_KEY is a {actual} key. "
                f"A live key in a test environment charges real cards; a test key in "
                f"production takes no money at all."
            )

        return self

    @model_validator(mode="after")
    def _refuse_unsafe_production_config(self) -> "Settings":
        """Refuse to start a production app with development shortcuts enabled.

        Both bypasses are catastrophic in production and neither has a visible
        symptom: with auth_bypass, every request arriving without an
        Authorization header is treated as an admin, so the whole admin API is
        open to anyone who finds the URL; with stripe_bypass, checkout creates
        orders inline without ever charging a card. A copied .env or a stale
        task definition is all it takes, and the app would otherwise come up
        looking perfectly healthy.

        Failing to boot is the point. A deployment that will not start gets
        noticed within minutes; one that starts wide open does not.
        """
        if self.app_env.lower() not in PRODUCTION_ENVS:
            return self

        problems = []
        if self.auth_bypass:
            problems.append("AUTH_BYPASS must be false (it makes every unauthenticated request an admin)")
        if self.stripe_bypass:
            problems.append("STRIPE_BYPASS must be false (it creates orders without charging)")
        if self.email_bypass:
            problems.append(
                "EMAIL_BYPASS must be false "
                "(customers would be charged and never told their order exists)"
            )
        if not self.email_from:
            problems.append("EMAIL_FROM is required (SES will not send from an unverified identity)")
        if not self.stripe_secret_key.get_secret_value():
            problems.append("STRIPE_SECRET_KEY is required")
        if not self.stripe_webhook_secret.get_secret_value():
            problems.append("STRIPE_WEBHOOK_SECRET is required (orders are created by the webhook)")
        if not self.cognito_user_pool_client_id:
            problems.append(
                "COGNITO_USER_POOL_CLIENT_ID is required "
                "(without it, a token from any app client in the pool is accepted)"
            )

        if problems:
            raise ValueError(
                f"Unsafe configuration for APP_ENV={self.app_env!r}: " + "; ".join(problems)
            )
        return self


@lru_cache
def get_settings() -> Settings:
    return Settings()
